name: Publish Package
description: 'Publish the package to rubygems'
inputs:
  dry_run:
    description: 'Is this a dry run. If so no package will be published.'
    required: true

runs:
  using: composite
  steps:
    - name: Build gemspec
      shell: bash
      run: gem build ld-eventsource.gemspec

    - name: Publish Library
      shell: bash
      if: ${{ inputs.dry_run == 'false' }}
      run: gem push ld-eventsource-*.gem
