name: CI Workflow
description: "Shared CI workflow."
inputs:
  ruby-version:
    description: "The version of ruby to setup and run"
    required: true

runs:
  using: composite
  steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby-version }}

    - name: Install dependencies
      shell: bash
      run: bundle install

    - name: Skip end to end tests for jruby
      if: ${{ startsWith(inputs.ruby-version, 'jruby') }}
      shell: bash
      run: echo "LD_SKIP_END_TO_END_HTTP_TESTS='y'" >> $GITHUB_ENV

    - name: Run tests
      shell: bash
      run: bundle exec rspec spec

    - name: Run RuboCop
      shell: bash
      run: bundle exec rubocop --parallel

    - name: Run contract tests
      if: ${{ !startsWith(inputs.ruby-version, 'jruby') }}
      shell: bash
      run: make contract-tests
