name: CI Workflow
description: "Shared CI workflow."
inputs:
  ruby-version:
    description: "The version of ruby to setup and run"
    required: true
  token:
    description: "GH token used to fetch the SDK test harness"
    required: true

runs:
  using: composite
  steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby-version }}

    - name: Install dependencies
      shell: bash
      run: bundle install

    - name: Skip end to end tests for jruby
      if: ${{ startsWith(inputs.ruby-version, 'jruby') }}
      shell: bash
      run: echo "LD_SKIP_END_TO_END_HTTP_TESTS='y'" >> $GITHUB_ENV

    - name: Run tests
      shell: bash
      run: bundle exec rspec spec

    - name: Run RuboCop
      if: ${{ !startsWith(inputs.ruby-version, 'jruby') }}
      shell: bash
      run: bundle exec rubocop --parallel

    - name: Build contract tests
      if: ${{ !startsWith(inputs.ruby-version, 'jruby') }}
      shell: bash
      run: make build-contract-tests

    - name: Start contract test service
      if: ${{ !startsWith(inputs.ruby-version, 'jruby') }}
      shell: bash
      run: make start-contract-test-service-bg

    - uses: launchdarkly/gh-actions/actions/contract-tests@contract-tests-v1.1.0
      if: ${{ !startsWith(inputs.ruby-version, 'jruby') }}
      with:
        test_service_port: 8000
        token: ${{ inputs.token }}
        repo: sse-contract-tests
        branch: main
